spring.application.name=Session14

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.cache=false
spring.thymeleaf.suffix=.html


spring.datasource.url=jdbc:mysql://localhost:3306/ss14?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=123456